### ISSUE TITLE
the cursor is stucking when i use the phone

### ISSUE THREAD

**Issue by Temouchenty** [alp1x/um-hackerphone#1]
the cursor is stucking when i use the phone

**Comment by alp1x** [comment]
Can you post this as a video?

**Comment by alp1x** [comment]
> the cursor is stucking when i use the phone

Can you post this as a video?

**Comment by Temouchenty** [comment]
https://user-images.githubusercontent.com/71113131/140771027-f64b62ba-8416-49a0-8c82-f684cfa2d277.mp4
