### ISSUE TITLE
Character movement problem

### ISSUE THREAD

**Issue by ZKing994** [alp1x/um-hackerphone#2]
When I use a hackerphone, my lens still rotates with the mouse. And after I close the hackerphone, no matter what I do, including typing in the T chat box, the lens will rotate with the mouse, and the characters will also move when I type text.

**Comment by alp1x** [comment]
> When I use a hackerphone, my lens still rotates with the mouse. And after I close the hackerphone, no matter what I do, including typing in the T chat box, the lens will rotate with the mouse, and the characters will also move when I type text.

fixed.

**Comment by ZKing994** [comment]
> > When I use a hackerphone, my lens still rotates with the mouse. And after I close the hackerphone, no matter what I do, including typing in the T chat box, the lens will rotate with the mouse, and the characters will also move when I type text.
> 
> fixed.

what??
